name: qqn
channels:
  - conda-forge
  - pytorch
dependencies:
  - python~=3.9
  - pytorch~=1.10
  - pyro-ppl~=1.7
  - cudatoolkit~=11.3
  - tqdm~=4.62
  - matplotlib
  - six~=1.16
  - seaborn
  - pip
  - pip:
      - effect~=1.1.0
      - frozendict~=2.1.1
      - frozenlist~=1.2.0