name: qqn
channels:
  - conda-forge
  - pytorch
dependencies:
  - python~=3.9
  - pytorch~=1.10
  - pyro-ppl~=1.7
  - cudatoolkit~=11.3
  - tqdm~=4.62
  - matplotlib~=3.5.0
  - six~=1.16
  - seaborn~=0.11.2
  - cachetools~=4.2.4
  - pip>=21.3.1
  - pip:
      - effect~=1.1.0
      - frozendict~=2.1.1
      - frozenlist~=1.2.0